(()=>{'use strict';const {filterCases,escapeHTML:e,sourceKey,caseHash,fromHash}=CaseAtlas;const cases=(window.CASE_DATA?.cases||window.CASE_DATA||[]).slice().sort((a,b)=>a.year-b.year||a.id.localeCompare(b.id));const $=s=>document.querySelector(s);const dialog=$('#detail');let lastFocus=null,routePushed=false,scrollBefore=0;
const link=(url,text)=>`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(text)}</a>`;
function citations(c,ids=[]){return ids.map(id=>{const s=c.sources.find(x=>x.id===id);return s?`<a class="citation" href="${e(s.url)}" target="_blank" rel="noopener noreferrer" aria-label="來源：${e(s.publisher)}，${e(s.title)}">[${e(id)}]</a>`:'';}).join('');}
function paragraph(c,item){if(typeof item==='string')return e(item);return `${e(item?.text||item?.description||'')}${citations(c,item?.sourceIds||[])}`;}
const categories=[...new Set(cases.map(c=>c.category))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));categories.forEach(c=>$('#category').add(new Option(c,c)));
function render(){const found=filterCases(cases,{query:$('#search').value,decade:$('#decade').value,category:$('#category').value});$('#count').textContent=`顯示 ${found.length} / ${cases.length} 件`;$('#empty').hidden=!!found.length;$('#cards').innerHTML=found.map(c=>`<article class="card"><div class="card-visual" aria-label="${c.year} 年案件分類示意"><span class="card-year">${c.year}</span><span class="case-no">FILE ${String(cases.indexOf(c)+1).padStart(2,'0')}</span><small class="visual-label">分類示意 · 非案發照片</small></div><div class="card-body"><span class="category-label">${e(c.category)}</span><h3><a href="${caseHash(c)}">${e(c.title)}</a></h3><p class="card-summary">${e(c.summary)}</p><div class="card-citations">${citations(c,c.summarySourceIds||c.event?.sourceIds||[])}</div><div class="card-status"><span>${e(c.status.label)}</span><small>主要狀態日期 ${e(c.status.asOf)}</small></div></div></article>`).join('');}
$('#filters').addEventListener('submit',ev=>ev.preventDefault());$('#search').addEventListener('input',render);$('#decade').addEventListener('change',render);$('#category').addEventListener('change',render);$('#clear-search').addEventListener('click',()=>{$('#search').value='';render();$('#search').focus();});$('#filters').addEventListener('reset',()=>{queueMicrotask(render);});$('#empty-reset').addEventListener('click',()=>{$('#filters').reset();$('#search').focus();});
function renderDetail(c){$('#detail-content').innerHTML=`<article class="detail-inner"><div class="detail-kicker">${e(c.year)} / ${e(c.category)} / FILE ${String(cases.indexOf(c)+1).padStart(2,'0')}</div><h2 id="detail-title">${e(c.title)}</h2><p class="detail-lead">${e(c.summary)}${citations(c,c.summarySourceIds||c.event?.sourceIds||[])}</p><div class="status-box"><h3>${e(c.status.label)}</h3><time class="asof">主要狀態日期 ${e(c.status.asOf)}</time><p>${paragraph(c,c.status)}</p></div><section class="detail-section"><h3>事件概述</h3><p>${paragraph(c,c.event)}</p></section>${c.judicial_status?.length?`<section class="detail-section"><h3>分開看各項司法程序</h3>${c.judicial_status.map(j=>`<div class="status-box"><h3>${e(j.proceeding||j.procedure||j.label||j.type||'司法程序')} ${j.finality?`· ${e(j.finality)}`:''}</h3>${j.asOf?`<time class="asof">截至 ${e(j.asOf)}</time>`:''}<p>${paragraph(c,j)}</p></div>`).join('')}</section>`:''}<section class="detail-section"><h3>事件與司法時間線</h3><ol class="timeline">${c.timeline.map(t=>`<li><time>${e(t.date)}</time><h4>${e(t.title)}</h4><p>${paragraph(c,t)}</p></li>`).join('')}</ol></section><section class="detail-section"><h3>制度討論</h3><ul class="impact-list">${c.impact.map(i=>`<li>${paragraph(c,i)}</li>`).join('')}</ul></section>${c.caveat?`<p class="caveat"><strong>閱讀限制</strong><br>${paragraph(c,c.caveat)}</p>`:''}<section class="detail-section"><h3>本案來源</h3><ol class="detail-sources">${c.sources.map(s=>`<li id="source-${e(c.id)}-${e(s.id)}">${link(s.url,s.title)}<small>${e(s.publisher)} · ${e(s.type)} · ${e(s.date||'日期未標示')} · [${e(s.id)}]</small></li>`).join('')}</ol></section><a class="permalink" href="${caseHash(c)}">本案固定連結：${e(c.title)}</a></article>`;document.title=`${c.title}｜台灣重大刑事案件圖鑑`;}
function route(){const c=fromHash(cases,location.hash);if(c){if(!dialog.open){lastFocus=document.activeElement;scrollBefore=window.scrollY;dialog.showModal();document.body.classList.add('modal-open');}renderDetail(c);dialog.scrollTop=0;$('#close-detail').focus();}else{if(dialog.open){dialog.close();document.body.classList.remove('modal-open');window.scrollTo(0,scrollBefore);if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}document.title='台灣重大刑事案件圖鑑｜事件・司法・制度';}}
function closeDetail(){if(routePushed){routePushed=false;history.back();}else{history.replaceState(null,'',`${location.pathname}${location.search}#catalog`);route();}}
$('#cards').addEventListener('click',ev=>{const a=ev.target.closest('a[href^="#case/"]');if(a&&!ev.ctrlKey&&!ev.metaKey&&!ev.shiftKey&&!ev.altKey){ev.preventDefault();history.pushState(null,'',a.getAttribute('href'));routePushed=true;route();}});$('#close-detail').addEventListener('click',closeDetail);dialog.addEventListener('cancel',ev=>{ev.preventDefault();closeDetail();});dialog.addEventListener('click',ev=>{if(ev.target===dialog){const r=dialog.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)closeDetail();}});window.addEventListener('hashchange',route);window.addEventListener('popstate',route);
const unique=new Map();cases.forEach(c=>c.sources.forEach(s=>{if(!unique.has(s.url))unique.set(s.url,{...s,caseTitles:[c.title]});else unique.get(s.url).caseTitles.push(c.title);}));const groups=new Map();[...unique.values()].forEach(s=>{const key=sourceKey(s);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(s);});$('#source-count').textContent=`${unique.size} 份來源`;$('#source-groups').innerHTML=[...groups.entries()].sort((a,b)=>a[0].localeCompare(b[0],'zh-Hant')).map(([name,ss])=>`<details class="source-group"><summary>${e(name)} · ${ss.length} 份</summary><ol>${ss.map(s=>`<li>${link(s.url,s.title)}<small>${e(s.date||'日期未標示')} · ${e(s.caseTitles.join('、'))}</small></li>`).join('')}</ol></details>`).join('');render();route();})();
