/* Run only against the approved public deployment, not a local-server workaround. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const url=process.env.ATLAS_URL;assert.ok(url&&url.startsWith('https://'),'Set ATLAS_URL to public HTTPS deployment');const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(url,{waitUntil:'networkidle'});assert.equal(await page.locator('.card').count(),40);await page.screenshot({path:'/tmp/taiwan-atlas-desktop.png',fullPage:false});
for(let i=0;i<3;i++){await page.locator('#search').fill('zzzz不存在xyz');assert.equal(await page.locator('.card').count(),0);assert.equal(await page.locator('#empty').isVisible(),true);await page.locator('#clear-search').click();assert.equal(await page.locator('.card').count(),40);}await page.locator('#search').fill('交通');assert.ok(await page.locator('.card').count()>0);await page.locator('#search').fill('zzzz不存在xyz');await page.locator('#empty-reset').click();assert.equal(await page.locator('.card').count(),40);
for(const d of ['1990','2000','2010','2020']){await page.locator('#decade').selectOption(d);const years=await page.locator('.card-year').allTextContents();assert.ok(years.every(y=>Math.floor(Number(y)/10)*10===Number(d)));}await page.locator('#filters button[type=reset]').click();assert.equal(await page.locator('.card').count(),40);const cats=await page.locator('#category option').evaluateAll(es=>es.slice(1).map(e=>e.value));for(const c of cats){await page.locator('#category').selectOption(c);assert.ok(await page.locator('.card').count()>0);assert.ok((await page.locator('.category-label').allTextContents()).every(x=>x===c));}await page.locator('#filters button[type=reset]').click();
await page.locator('#life').selectOption('yes');assert.equal(await page.locator('.card').count(),30);await page.locator('#nature').selectOption('事故／公共安全');assert.ok(await page.locator('.card').count()>0);await page.locator('#filters button[type=reset]').click();assert.equal(await page.locator('.card').count(),40);assert.equal(await page.locator('#life').inputValue(),'all');assert.equal(await page.locator('#nature').inputValue(),'all');
const href=await page.locator('.card h3 a').first().getAttribute('href');await page.locator('.card h3 a').first().click();assert.equal(await page.locator('#detail').isVisible(),true);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#detail').open);await page.locator('.card h3 a').first().click();await page.goBack();assert.equal(await page.locator('#detail').isVisible(),false);await page.goto(url+href);assert.equal(await page.locator('#detail').isVisible(),true);assert.ok(await page.locator('.timeline li').count()>=2);await page.locator('#close-detail').click();assert.equal(await page.locator('#detail').isVisible(),false);
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`catalog overflow ${width}`);await page.locator('.card h3 a').first().click();assert.ok(await page.evaluate(()=>document.querySelector('#detail').scrollWidth<=innerWidth),`detail overflow ${width}`);await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#detail').open);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/taiwan-atlas-mobile.png',fullPage:false});await page.locator('.card h3 a').first().click();await page.screenshot({path:'/tmp/taiwan-atlas-detail-mobile.png',fullPage:false});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: public browser desktop/mobile 1440/768/390/320, search repeat/clear/no-result, filters/reset, deep link, Back/Escape, no console errors/overflow');})().catch(e=>{console.error(e);process.exit(1)});
