const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/cases.json'),'utf8'));const cases=data.cases||data;const logic=require('../logic.js');assert.equal(cases.length,40,'40 cases');assert.equal(new Set(cases.map(c=>c.id)).size,40,'unique ids');assert.equal(new Set(cases.map(c=>c.slug||c.id)).size,40,'unique routes');
for(const c of cases){assert.ok(Array.isArray(c.judicial_status),'explicit procedure array');assert.match(c.id,/^[a-z0-9-]+$/);assert.ok(c.year>=1996&&c.year<=2025);for(const k of ['title','category','summary'])assert.ok(c[k],`${c.id} ${k}`);assert.ok(c.status.label&&c.status.text&&c.status.asOf);assert.match(c.status.asOf,/^\d{4}-\d{2}-\d{2}$/);assert.ok(c.event.text);assert.ok(c.timeline.length>=2);assert.ok(c.impact.length);assert.ok(c.sources.length>=1);const ids=new Set(c.sources.map(s=>s.id));assert.equal(ids.size,c.sources.length);for(const s of c.sources){assert.ok(s.publisher&&s.type&&s.title);assert.notEqual(s.publisher,'發布者待補核');assert.ok(new URL(s.url).protocol==='https:');}const claims=[{sourceIds:c.summarySourceIds||c.event.sourceIds},c.event,c.status,...c.timeline,...c.impact,...(c.judicial_status||[])];for(const claim of claims){assert.ok(claim.sourceIds?.length,`${c.id} claim missing citations`);for(const id of claim.sourceIds)assert.ok(ids.has(id),`${c.id} broken ref ${id}`);}for(const t of c.timeline)assert.ok(t.date&&t.title&&t.text);assert.equal(logic.fromHash(cases,logic.caseHash(c)),c);assert.equal(logic.fromHash(cases,`#${c.id}`),c);assert.ok(logic.filterCases(cases,{query:c.title}).includes(c));}
assert.equal(logic.filterCases(cases).length,40);assert.equal(logic.filterCases(cases,{query:'沒有這個案件xyz123'}).length,0);for(const decade of ['1990','2000','2010','2020'])for(const c of logic.filterCases(cases,{decade}))assert.equal(Math.floor(c.year/10)*10,Number(decade));for(const category of new Set(cases.map(c=>c.category)))for(const c of logic.filterCases(cases,{category}))assert.equal(c.category,category);assert.equal(logic.fromHash(cases,'#case/%xx'),null);assert.equal(logic.escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;');assert.equal(logic.sourceKey({publisher:'法院',type:'裁判',url:'https://news.test'}),'法院｜裁判');
const forbiddenKeys=['photo','portrait','address','offender','suspect','prison','releaseDate','personalProfile'];const all=JSON.stringify(data);for(const key of forbiddenKeys)assert.ok(!all.includes(`"${key}"`),`private profile field ${key}`);console.log('PASS: 40 cases, unique routes, citations, dates, filter combinations, legacy anchors, schema privacy');

assert.equal(cases.filter(c=>c.life_focus).length,30);assert.equal(cases.filter(c=>c.cohort==='original20').length,20);assert.equal(logic.filterCases(cases,{life:'yes'}).length,30);assert.equal(logic.filterCases(cases,{life:'no'}).length,10);
for(const c of cases){const s=c.editorial_score;assert.equal(s.base_max,100);assert.equal(s.adjusted_max,110);assert.equal(s.threshold,70);assert.equal(s.base,Object.values(s.dimensions).reduce((sum,d)=>sum+d.score,0));assert.equal(s.total,s.base+s.bonus);assert.ok([0,5,10].includes(s.bonus));const ids=new Set(c.sources.map(s=>s.id));for(const d of Object.values(s.dimensions)){assert.ok(d.reason);assert.ok(d.score>=0&&d.score<=20);assert.ok(d.sourceIds.length);for(const id of d.sourceIds)assert.ok(ids.has(id),`${c.id} score ref ${id}`);}for(const id of s.bonus_sourceIds)assert.ok(ids.has(id),`${c.id} bonus ref ${id}`);if(s.bonus)assert.ok(s.bonus_sourceIds.length);for(const q of c.learning_questions){assert.ok(q.sourceIds.length);for(const id of q.sourceIds)assert.ok(ids.has(id),`${c.id} question ref ${id}`);}assert.ok(c.event_natures.length);for(const nature of c.event_natures)assert.ok(logic.filterCases(cases,{nature,life:c.life_focus?'yes':'no',category:c.category,query:c.title,decade:String(Math.floor(c.year/10)*10)}).includes(c));}
const retained=cases.find(c=>c.id==='taoyuan-family-arson-2016').editorial_score;assert.deepEqual([retained.base,retained.bonus,retained.total],[40,10,50]);console.log('PASS: 40/30 counts, score arithmetic and sources, multi-value nature intersections, original exception preserved');

for(const c of cases){const ids=new Set(c.sources.map(s=>s.id));for(const note of [c.nature_note,c.judicial_review_note].filter(Boolean)){assert.ok(note.text&&note.sourceIds.length);for(const id of note.sourceIds)assert.ok(ids.has(id));}}
